# Generated by Django 3.1.2 on 2021-02-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='removed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
