# Generated by Django 3.1.2 on 2021-02-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20210207_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sign',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
